name: 代码质量测试

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  unit-test:
    name: 单元测试
    runs-on: ubuntu-slim
    # TODO
    if: 0
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: .tool-versions
      - run: bun ci
      - run: bun run test

  type-check:
    name: 类型检查
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: .tool-versions
      - run: bun ci
      - run: bun run build:web
      - run: bun run --config=bunfig.vue-tsc.toml type-check
